# This is a basic workflow to help you get started with Actions

name: GitLab CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the 2-modify-homepage branch
  push:
    branches: [ 2-modify-homepage ]
  pull_request:
    branches: [ 2-modify-homepage ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: trigger Job
        uses: appleboy/gitlab-ci-action@master
        with:
            host: "https://gitlab.com"
            token: "957f5ebce6cf4b2a12d1512804e00f"
            debug: "true" 
            project_id: 22925079
            ref: "master"
